version: '3.1'

services:
  mysql_db:
    image: mysql:8
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: docker_DB
      MYSQL_USER: zem
      MYSQL_PASSWORD: zem